// Generated by gencpp from file ros_opencart/GetCurrentOrders.msg
// DO NOT EDIT!


#ifndef ROS_OPENCART_MESSAGE_GETCURRENTORDERS_H
#define ROS_OPENCART_MESSAGE_GETCURRENTORDERS_H

#include <ros/service_traits.h>


#include <ros_opencart/GetCurrentOrdersRequest.h>
#include <ros_opencart/GetCurrentOrdersResponse.h>


namespace ros_opencart
{

struct GetCurrentOrders
{

typedef GetCurrentOrdersRequest Request;
typedef GetCurrentOrdersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrentOrders
} // namespace ros_opencart


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_opencart::GetCurrentOrders > {
  static const char* value()
  {
    return "50e0ba130e3fdef0430aac43454e1263";
  }

  static const char* value(const ::ros_opencart::GetCurrentOrders&) { return value(); }
};

template<>
struct DataType< ::ros_opencart::GetCurrentOrders > {
  static const char* value()
  {
    return "ros_opencart/GetCurrentOrders";
  }

  static const char* value(const ::ros_opencart::GetCurrentOrders&) { return value(); }
};


// service_traits::MD5Sum< ::ros_opencart::GetCurrentOrdersRequest> should match 
// service_traits::MD5Sum< ::ros_opencart::GetCurrentOrders > 
template<>
struct MD5Sum< ::ros_opencart::GetCurrentOrdersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opencart::GetCurrentOrders >::value();
  }
  static const char* value(const ::ros_opencart::GetCurrentOrdersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opencart::GetCurrentOrdersRequest> should match 
// service_traits::DataType< ::ros_opencart::GetCurrentOrders > 
template<>
struct DataType< ::ros_opencart::GetCurrentOrdersRequest>
{
  static const char* value()
  {
    return DataType< ::ros_opencart::GetCurrentOrders >::value();
  }
  static const char* value(const ::ros_opencart::GetCurrentOrdersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_opencart::GetCurrentOrdersResponse> should match 
// service_traits::MD5Sum< ::ros_opencart::GetCurrentOrders > 
template<>
struct MD5Sum< ::ros_opencart::GetCurrentOrdersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opencart::GetCurrentOrders >::value();
  }
  static const char* value(const ::ros_opencart::GetCurrentOrdersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opencart::GetCurrentOrdersResponse> should match 
// service_traits::DataType< ::ros_opencart::GetCurrentOrders > 
template<>
struct DataType< ::ros_opencart::GetCurrentOrdersResponse>
{
  static const char* value()
  {
    return DataType< ::ros_opencart::GetCurrentOrders >::value();
  }
  static const char* value(const ::ros_opencart::GetCurrentOrdersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_OPENCART_MESSAGE_GETCURRENTORDERS_H
