// Generated by gencpp from file ros_opencart/UpdateOrderResponse.msg
// DO NOT EDIT!


#ifndef ROS_OPENCART_MESSAGE_UPDATEORDERRESPONSE_H
#define ROS_OPENCART_MESSAGE_UPDATEORDERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_opencart
{
template <class ContainerAllocator>
struct UpdateOrderResponse_
{
  typedef UpdateOrderResponse_<ContainerAllocator> Type;

  UpdateOrderResponse_()
    : errorcode(0)
    , errormsg()  {
    }
  UpdateOrderResponse_(const ContainerAllocator& _alloc)
    : errorcode(0)
    , errormsg(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _errorcode_type;
  _errorcode_type errorcode;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _errormsg_type;
  _errormsg_type errormsg;




  typedef boost::shared_ptr< ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateOrderResponse_

typedef ::ros_opencart::UpdateOrderResponse_<std::allocator<void> > UpdateOrderResponse;

typedef boost::shared_ptr< ::ros_opencart::UpdateOrderResponse > UpdateOrderResponsePtr;
typedef boost::shared_ptr< ::ros_opencart::UpdateOrderResponse const> UpdateOrderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_opencart

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ros_opencart': ['/home/christian/ros_opencart/src/ros_opencart/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e319c82db71f71b97ee127420ee9a397";
  }

  static const char* value(const ::ros_opencart::UpdateOrderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe319c82db71f71b9ULL;
  static const uint64_t static_value2 = 0x7ee127420ee9a397ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_opencart/UpdateOrderResponse";
  }

  static const char* value(const ::ros_opencart::UpdateOrderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 errorcode\n\
string errormsg\n\
\n\
";
  }

  static const char* value(const ::ros_opencart::UpdateOrderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.errorcode);
      stream.next(m.errormsg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateOrderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_opencart::UpdateOrderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_opencart::UpdateOrderResponse_<ContainerAllocator>& v)
  {
    s << indent << "errorcode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.errorcode);
    s << indent << "errormsg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.errormsg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_OPENCART_MESSAGE_UPDATEORDERRESPONSE_H
