// Generated by gencpp from file ros_opencart/UpdateOrderRequest.msg
// DO NOT EDIT!


#ifndef ROS_OPENCART_MESSAGE_UPDATEORDERREQUEST_H
#define ROS_OPENCART_MESSAGE_UPDATEORDERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_opencart
{
template <class ContainerAllocator>
struct UpdateOrderRequest_
{
  typedef UpdateOrderRequest_<ContainerAllocator> Type;

  UpdateOrderRequest_()
    : id(0)
    , status()  {
    }
  UpdateOrderRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateOrderRequest_

typedef ::ros_opencart::UpdateOrderRequest_<std::allocator<void> > UpdateOrderRequest;

typedef boost::shared_ptr< ::ros_opencart::UpdateOrderRequest > UpdateOrderRequestPtr;
typedef boost::shared_ptr< ::ros_opencart::UpdateOrderRequest const> UpdateOrderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_opencart

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ros_opencart': ['/home/christian/ros_opencart/src/ros_opencart/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42ae6a703cf494ba9a3579ce85ddd530";
  }

  static const char* value(const ::ros_opencart::UpdateOrderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42ae6a703cf494baULL;
  static const uint64_t static_value2 = 0x9a3579ce85ddd530ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_opencart/UpdateOrderRequest";
  }

  static const char* value(const ::ros_opencart::UpdateOrderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
string status\n\
";
  }

  static const char* value(const ::ros_opencart::UpdateOrderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateOrderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_opencart::UpdateOrderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_opencart::UpdateOrderRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_OPENCART_MESSAGE_UPDATEORDERREQUEST_H
