// Generated by gencpp from file ros_opencart/UpdateOrder.msg
// DO NOT EDIT!


#ifndef ROS_OPENCART_MESSAGE_UPDATEORDER_H
#define ROS_OPENCART_MESSAGE_UPDATEORDER_H

#include <ros/service_traits.h>


#include <ros_opencart/UpdateOrderRequest.h>
#include <ros_opencart/UpdateOrderResponse.h>


namespace ros_opencart
{

struct UpdateOrder
{

typedef UpdateOrderRequest Request;
typedef UpdateOrderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateOrder
} // namespace ros_opencart


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_opencart::UpdateOrder > {
  static const char* value()
  {
    return "55217c91459788b418c545e3f81d882e";
  }

  static const char* value(const ::ros_opencart::UpdateOrder&) { return value(); }
};

template<>
struct DataType< ::ros_opencart::UpdateOrder > {
  static const char* value()
  {
    return "ros_opencart/UpdateOrder";
  }

  static const char* value(const ::ros_opencart::UpdateOrder&) { return value(); }
};


// service_traits::MD5Sum< ::ros_opencart::UpdateOrderRequest> should match 
// service_traits::MD5Sum< ::ros_opencart::UpdateOrder > 
template<>
struct MD5Sum< ::ros_opencart::UpdateOrderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opencart::UpdateOrder >::value();
  }
  static const char* value(const ::ros_opencart::UpdateOrderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opencart::UpdateOrderRequest> should match 
// service_traits::DataType< ::ros_opencart::UpdateOrder > 
template<>
struct DataType< ::ros_opencart::UpdateOrderRequest>
{
  static const char* value()
  {
    return DataType< ::ros_opencart::UpdateOrder >::value();
  }
  static const char* value(const ::ros_opencart::UpdateOrderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_opencart::UpdateOrderResponse> should match 
// service_traits::MD5Sum< ::ros_opencart::UpdateOrder > 
template<>
struct MD5Sum< ::ros_opencart::UpdateOrderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_opencart::UpdateOrder >::value();
  }
  static const char* value(const ::ros_opencart::UpdateOrderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_opencart::UpdateOrderResponse> should match 
// service_traits::DataType< ::ros_opencart::UpdateOrder > 
template<>
struct DataType< ::ros_opencart::UpdateOrderResponse>
{
  static const char* value()
  {
    return DataType< ::ros_opencart::UpdateOrder >::value();
  }
  static const char* value(const ::ros_opencart::UpdateOrderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_OPENCART_MESSAGE_UPDATEORDER_H
